### ISSUE TITLE
StatusCode= ServiceUnavailable ReasonPhrase= Service Unavailable

### ISSUE THREAD

**Issue by Iagofelicio** [multicanais/ons-sintegre-webhook#1]
Estou recebendo este retorno de erro, na interface do SINtegre. 
Status: StatusCode= ServiceUnavailable ReasonPhrase= Service Unavailable

Entretanto, minha aplicação que usa um Webhook Client para Laravel está funcionando quando testo com o Postman. 
Obs.: https://github.com/spatie/laravel-webhook-client

Gostaria de saber quais as possíveis causas para o erro acima para que eu possa entender o que pode ser feito ou se o erro não poderia estar vindo do server de vocês. 

Obs.2: Estou usando o ngrok pra gerar um link publico para meu client.

**Comment by Iagofelicio** [comment]
**[Mais detalhes]**
As 15:15:30 foi realizado uma tentativa de envio para meu webhook que não foi acionada por mim nem por ninguém da minha equipe. 

Como podemos ver na imagem a seguir: [https://imgur.com/a/zfZ0ptf](https://imgur.com/a/Qk2EKsd)

No log do NGROK, consta uma tentativa de request usando o método GET, conforme imagem a seguir: [https://imgur.com/a/zfZ0ptf](https://imgur.com/a/zfZ0ptf)

Contudo, a documentção para configuração do webhook diz: 

> Informe um usuário e senha para que o SINtegre, ao enviar o POST, se autentique na URL
> informada através da autenticação básica. Também é possível informar um token para que o
> SINtegre, ao enviar o POST, envie o token informado para que seu webhook realize a validação. 

Não deveria ser uma requisição POST? O server de vocẽs não está tentando enviar uma requisição GET no lugar?

**Comment by multicanais** [comment]
Prezado Iago,

 

Infelizmente ainda não suportamos ngrok, os servidores do SINtegre não acessam. Estamos verificando a viabilidade de liberar nosso firewall para enviar os posts para estas urls.

 

At,



	
		
			
			
			
			
			
			Anderson Gulão 
			Analista de TI
			Gerência de Manutenção de Aplicações de Suporte ao Negócio
			Diretoria de TI, Relacionamento com Agentes e Assuntos Regulatórios
			Tel: 21 3444-9295
			www.ons.org.br 
		
	


Antes de imprimir, pense em seu compromisso com o meio ambiente.


 

 

----- Mensagem original -----
De: "Iago Felicio" <notifications@github.com>
Para: "multicanais/ons-sintegre-webhook" <ons-sintegre-webhook@noreply.github.com>
Cc: "Subscribed" <subscribed@noreply.github.com>
Assunto: Re: [multicanais/ons-sintegre-webhook] StatusCode= ServiceUnavailable ReasonPhrase= Service Unavailable (#1)
Data: sex, 11 de out de 2019 15:23
 
[Mais detalhes]
As 15:15:30 foi realizado uma tentativa de envio para meu webhook que não foi acionada por mim nem por ninguém da minha equipe.

Como podemos ver na imagem a seguir: https://imgur.com/a/zfZ0ptf

No log do NGROK, consta uma tentativa de request usando o método GET, conforme imagem a seguir: https://imgur.com/a/zfZ0ptf

Contudo, a documentção para configuração do webhook diz:


Informe um usuário e senha para que o SINtegre, ao enviar o POST, se autentique na URL
informada através da autenticação básica. Também é possível informar um token para que o
SINtegre, ao enviar o POST, envie o token informado para que seu webhook realize a validação.


Não deveria ser uma requisição POST? O server de vocẽs não está tentando enviar uma requisição GET no lugar?

**Comment by tscher** [comment]
Estou tendo o mesmo problema, tentei tanto com o ngrok quanto o serveo.net sem sucesso.
Acho válido colocarem um warming comentando esse block do lado de vocês, pois perdi algum tempo debugando algo que não estava errado!

**Comment by tscher** [comment]
Alguma previsão para libera o firewall para o ngrok e/ou serveo?

**Comment by multicanais** [comment]
[ngrok] (https://ngrok.com/) foi liberado, agora os servidores do SINtegre conseguem enviar notificações para endereços HTTS do ngrok.

 

At,

 



	
		
			
			
			
			
			
			Anderson Gulão 
			Analista de TI
			Gerência de Manutenção de Aplicações de Suporte ao Negócio
			Diretoria de TI, Relacionamento com Agentes e Assuntos Regulatórios
			Tel: 21 3444-9295
			www.ons.org.br 
		
	


Antes de imprimir, pense em seu compromisso com o meio ambiente.


 

 

----- Mensagem original -----
De: "tscher" <notifications@github.com>
Para: "multicanais/ons-sintegre-webhook" <ons-sintegre-webhook@noreply.github.com>
Cc: "multicanais" <stm-multicanais@ons.org.br>, "State change" <state_change@noreply.github.com>
Assunto: Re: [multicanais/ons-sintegre-webhook] StatusCode= ServiceUnavailable ReasonPhrase= Service Unavailable (#1)
Data: sex, 25 de out de 2019 15:03
 
Alguma previsão para libera o firewall para o ngrok e/ou serveo?

**Comment by tscher** [comment]
Funcionando perfeitamente.

Muito obrigado.
